package(
  default_visibility = ["//visibility:public"],
)

load("@rules_cc//cc:defs.bzl", "cc_library")

cc_library(
  name = "vulkan",
  srcs = [
    "vulkan_android_wrapper.cpp",
  ],
  hdrs = [
    "vulkan_android_wrapper.h",
    "vulkan_wrapper.h",
  ]
)